version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "oblige-speak"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13ph2fuoerjaw"
s3_prefix = "oblige-speak"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides=[
  "OPENAI_API_KEY=Value1",
  "TemplateInput2=Value2"
]
